### ISSUE TITLE
Sign an ES256 or RS256 JWT within Postgres

### ISSUE THREAD

**Issue by daveycodez** [neondatabase/pg_session_jwt#21]
I want to build an auth system that directly connects to Postgres, but currently we can only sign keys with pgjwt that aren't compatible with JWKS. Is there any way to add a method for signing JWT's at the postgres level that can be used with RLS.

**Comment by conradludgate** [comment]
Hi, thanks for the issue. Currently pg_session_jwt only handles the _verification_ of ES256 JWTs. We don't have any intention to support signing at this time. 

Usually for an authentication platform you need to be doing some kind of oauth2 flow or password verification, and I would recommend signing JWTs at that place, not within Postgres.

**Comment by daveycodez** [comment]
The thinking is a future where there no longer needs to be an authentication API, and instead have a function within Postgres that an anonymous user can use, for example...

SELECT from users where email = '$email' and password = '$hashedPassword'

If found, sign and return JWT to be passed along in subsequent requests. The whole purpose being to totally remove the need for a separate API for handling authentication. Or is the only API-less future going to require using third party OAuth providers and their JWKS?
